package com.example.school.system.services;

import java.security.SecureRandom;
import java.time.LocalDateTime;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.example.school.system.DTO.OtpCreationDTO;
import com.example.school.system.DTO.OtpValidationDTO;
import com.example.school.system.error.OtpExceptionHandler;
import com.example.school.system.models.OTP;
import com.example.school.system.repository.OtpRepository;

@Service
public class OtpService {
    private OtpRepository otpRepository;

    public OtpService(OtpRepository otpRepository) {
        this.otpRepository = otpRepository;
    }

    @Transactional
    public String GenerateOtp(OtpCreationDTO otpDTO) {
        if (otpDTO.email() != null) {
            otpRepository.deleteByEmail(otpDTO.email().trim().toLowerCase());
        }
        String randomValue = RandomValues();

        otpRepository.save(toOtp(otpDTO, randomValue));
        return randomValue;
    }

    private OTP toOtp(OtpCreationDTO otpDTO, String randomValue) {
        OTP otp = new OTP();
        otp.setEmail(otpDTO.email());
        otp.setValue(randomValue);
        return otp;
    }

    private String RandomValues() {
        SecureRandom value = new SecureRandom();
        String securedString = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        StringBuilder autoGeneratedValue = new StringBuilder();
        for (int i = 0; i < 4; i++) {
            autoGeneratedValue.append(securedString.charAt(value.nextInt(securedString.length())));
        }
        return autoGeneratedValue.toString();

    }

    public String ValidateOtp(OtpValidationDTO otpDTO) {
        OTP otpFound = otpRepository.findOneByEmail(otpDTO.email())
                .orElseThrow(() -> new OtpExceptionHandler("Invalid Otp"));
        System.out.println("the otp in the database" + otpFound.getValue());
        if (!otpFound.getValue().equals(otpDTO.value()) || otpFound.isUsed()) {
            throw new OtpExceptionHandler("Invalid Otp");
        }
        otpFound.setUsed(true);
        otpRepository.save(otpFound);
        if (otpFound.getExpirationTime().isBefore(LocalDateTime.now())) {
            throw new OtpExceptionHandler("Invalid Otp");
        }
        return "OTP verified successfully";

    }
}
