package com.example.school.system.services;

import java.security.SecureRandom;
import org.springframework.stereotype.Component;

@Component
public class RandomValuesService {
    private String securedString = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

    public String RandomValues(int numberLoops) {
        SecureRandom value = new SecureRandom();

        StringBuilder autoGeneratedValue = new StringBuilder();
        for (int i = 0; i < numberLoops; i++) {
            autoGeneratedValue.append(securedString.charAt(value.nextInt(securedString.length())));
        }
        return autoGeneratedValue.toString();

    }

    public String RandomValues(int numberLoops, String message) {
        SecureRandom value = new SecureRandom();

        StringBuilder autoGeneratedValue = new StringBuilder();
        autoGeneratedValue.append(message);
        for (int i = 0; i < numberLoops; i++) {
            autoGeneratedValue.append(securedString.charAt(value.nextInt(securedString.length())));
        }
        return autoGeneratedValue.toString();

    }
}

