// components/deputyhead/shared/data.ts
export const TEACHERS = [
  {
    id: "T1",
    name: "Peter Otieno",
    subject: "Mathematics",
    class: "Grade 7A",
    students: 35,
    status: "Active",
    avg: 81,
    joinDate: "2019-01-10",
  },
  {
    id: "T2",
    name: "Jane Wanjiku",
    subject: "English",
    class: "Grade 8B",
    students: 32,
    status: "Active",
    avg: 74,
    joinDate: "2018-03-15",
  },
  {
    id: "T3",
    name: "James Kamau",
    subject: "Kiswahili",
    class: "Grade 7B",
    students: 34,
    status: "Active",
    avg: 79,
    joinDate: "2021-01-05",
  },
  {
    id: "T4",
    name: "Mary Achieng",
    subject: "Science",
    class: "Grade 9A",
    students: 30,
    status: "On leave",
    avg: 71,
    joinDate: "2020-06-20",
  },
  {
    id: "T5",
    name: "John Mwangi",
    subject: "Social Studies",
    class: "Grade 8A",
    students: 33,
    status: "Active",
    avg: 76,
    joinDate: "2017-09-01",
  },
  {
    id: "T6",
    name: "Grace Njeri",
    subject: "CRE",
    class: "Grade 9B",
    students: 29,
    status: "Active",
    avg: 83,
    joinDate: "2022-01-12",
  },
];

export const CLASSES = [
  {
    id: "C1",
    name: "Grade 7A",
    teacher: "Peter Otieno",
    students: 35,
    subjects: 5,
    avg: 78,
    term: 1,
  },
  {
    id: "C2",
    name: "Grade 7B",
    teacher: "James Kamau",
    students: 34,
    subjects: 5,
    avg: 74,
    term: 1,
  },
  {
    id: "C3",
    name: "Grade 8A",
    teacher: "John Mwangi",
    students: 33,
    subjects: 6,
    avg: 81,
    term: 1,
  },
  {
    id: "C4",
    name: "Grade 8B",
    teacher: "Jane Wanjiku",
    students: 32,
    subjects: 6,
    avg: 69,
    term: 1,
  },
  {
    id: "C5",
    name: "Grade 9A",
    teacher: "Mary Achieng",
    students: 30,
    subjects: 7,
    avg: 76,
    term: 1,
  },
  {
    id: "C6",
    name: "Grade 9B",
    teacher: "Grace Njeri",
    students: 29,
    subjects: 7,
    avg: 83,
    term: 1,
  },
];

export const STUDENTS = [
  {
    id: "S1",
    name: "Emma Mwangi",
    class: "Grade 7A",
    gender: "Female",
    status: "Active",
    avg: 88,
    adm: "2024/001",
  },
  {
    id: "S2",
    name: "James Otieno",
    class: "Grade 7A",
    gender: "Male",
    status: "Active",
    avg: 77,
    adm: "2024/002",
  },
  {
    id: "S3",
    name: "Aisha Hassan",
    class: "Grade 8A",
    gender: "Female",
    status: "Active",
    avg: 82,
    adm: "2023/045",
  },
  {
    id: "S4",
    name: "Brian Kipchoge",
    class: "Grade 8B",
    gender: "Male",
    status: "Active",
    avg: 65,
    adm: "2023/046",
  },
  {
    id: "S5",
    name: "Cynthia Achieng",
    class: "Grade 9A",
    gender: "Female",
    status: "Inactive",
    avg: 59,
    adm: "2022/031",
  },
  {
    id: "S6",
    name: "David Kamau",
    class: "Grade 9B",
    gender: "Male",
    status: "Active",
    avg: 91,
    adm: "2022/032",
  },
];

export const CONCERNS = [
  {
    id: "P1",
    parent: "Mr. John Mwangi",
    student: "Emma Mwangi",
    class: "Grade 7A",
    issue: "Requested grade review for Mathematics mid-term.",
    date: "2024-10-14",
    status: "Open",
    priority: "High",
  },
  {
    id: "P2",
    parent: "Mrs. Fatuma Ali",
    student: "Aisha Hassan",
    class: "Grade 8A",
    issue: "Query on school fees payment schedule.",
    date: "2024-10-12",
    status: "Resolved",
    priority: "Low",
  },
  {
    id: "P3",
    parent: "Mr. K. Kimutai",
    student: "Brian Kipchoge",
    class: "Grade 8B",
    issue: "Attendance record discrepancy in October.",
    date: "2024-10-10",
    status: "Open",
    priority: "Medium",
  },
  {
    id: "P4",
    parent: "Mrs. N. Njeri",
    student: "Cynthia Achieng",
    class: "Grade 9A",
    issue: "Request for special support and counselling.",
    date: "2024-10-08",
    status: "Pending",
    priority: "High",
  },
];

export const NAV_ALL = [
  {
    id: "overview",
    label: "School overview",
    desc: "Key metrics and schoolwide readiness.",
    icon: "M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z",
    icon2: "M9 22V12h6v10",
    roles: ["deputy", "headteacher"],
  },
  {
    id: "teachers",
    label: "Teacher management",
    desc: "Monitor staffing, workload, support.",
    icon: "M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2",
    icon2: "M23 21v-2a4 4 0 00-3-3.87M16 3.13a4 4 0 010 7.75",
    roles: ["deputy", "headteacher"],
  },
  {
    id: "classes",
    label: "Class management",
    desc: "Track streams and class assignments.",
    icon: "M4 19.5A2.5 2.5 0 016.5 17H20",
    icon2: "M6.5 2H20v20H6.5A2.5 2.5 0 014 19.5v-15A2.5 2.5 0 016.5 2z",
    roles: ["deputy", "headteacher"],
  },
  {
    id: "students",
    label: "Student management",
    desc: "Review learner records and movement.",
    icon: "M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2",
    icon2: "M12 11a4 4 0 100-8 4 4 0 000 8z",
    roles: ["deputy", "headteacher"],
  },
  {
    id: "exited",
    label: "Exited learners",
    desc: "Review inactive learners who completed the final grade.",
    icon: "M16 17l5-5-5-5",
    icon2: "M21 12H9M12 19H5a2 2 0 01-2-2V7a2 2 0 012-2h7",
    roles: ["deputy", "headteacher"],
  },
  {
    id: "analytics",
    label: "Analytics",
    desc: "Trends, attainment, and patterns.",
    icon: "M18 20V10M12 20V4M6 20v-6",
    roles: ["deputy", "headteacher"],
  },
  {
    id: "topStudents",
    label: "Best students",
    desc: "Top performers across all streams.",
    icon: "M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z",
    roles: ["deputy", "headteacher"],
  },
  {
    id: "reports",
    label: "Reports",
    desc: "Leadership summaries and packs.",
    icon: "M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z",
    icon2: "M14 2v6h6M16 13H8M16 17H8",
    roles: ["headteacher"],
  },
  {
    id: "concerns",
    label: "Parent concerns",
    desc: "Follow-up and family feedback.",
    icon: "M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z",
    roles: ["deputy", "headteacher"],
  },
];
