export const endpoints = {
  auth: {
    login: "/auth/login/login-user",
    createTeacherAccount: "/auth/teacher/create-account",
    currentUser: "/auth/me",
  },
  dashboard: {
    summary: "/dashboard/summary",
  },
  schools: {
    create: "/schools/create-school",
    update: "/schools/update/school",
    remove: "/schools/delete/school",
    forUser: "/schools/get/school/for/user",
  },
  classes: {
    classes: (schoolId: string) => `/all/classes/${schoolId}`,
    create: "/create/school/class",
    update: "/update/class",
    unassignTeacher: "/unassign/classteacher",
    updateCycle: (classId: string) => `/update/${classId}/school-cycle`,
  },
  subjects: {
    subjects: (schoolId: string) => `/getAll/subjects/${schoolId}`,
    subjectJoints: (schoolId: string) => `/get/all/subject-joints/${schoolId}`,
    create: "/create/subject",
    createMany: "/create/multiple/subjects",
    update: "/update/subject",
    updateJoint: "/update/subject-joint",
    registerJoint: "/register/subject-joint",
    registerStudentJoint: "/register/singlestudent/subject-joint",
    assignTeacher: "/assign/subject/teacher",
    unassignTeacher: "/unassign/subject/teacher",
  },
  users: {
    teachers: (schoolId: string) => `/users/${schoolId}/teachers`,
    teacherInvites: (userId: string) => `/users/get/invites/${userId}`,
    addTeacherProfile: "/users/teacher/add-profile",
    createTeacher: "/users/teacher",
    updateTeacher: "/users/update",
    update: "/update/user",
    remove: "/delete/user",
    suspend: "/suspend/user",
    deactivate: "/deactivate/user",
    dangerZoneDelete: "/danger-zone/delete/account",
  },
  students: {
    register: "/register/students",
    update: "/update/id",
    all: "/get/all/students",
    byClass: "/get/students",
  },
  attendance: {
    sheet: "/attendance/sheet",
    records: "/attendance/get/attendance-sheet",
    studentRecord: "/attendance/student/attendance/record",
    updateSheet: "/attendance/update/sheet",
  },
  marks: {
    sheet: (subjectJointId: string) => `/marks/${subjectJointId}`,
    entry: "/marks/entry",
  },
  timetable: {
    settings: "/timetables/settings",
    requirements: "/timetables/requirements",
    generate: "/timetables/generate",
    preview: (schoolId: string) => `/timetables/preview/${schoolId}`,
    regenerate: "/timetables/regenerate",
    bySchool: (schoolId: string) => `/timetables/${schoolId}`,
    validate: (schoolId: string) => `/timetables/validate/${schoolId}`,
    history: (schoolId: string) => `/timetables/history/${schoolId}`,
    conflicts: (historyId: string) => `/timetables/conflicts/${historyId}`,
  },
  grading: {
    scale: (schoolId: string) => `/create/grading-scale/${schoolId}`,
    updateScale: "/update/scale",
    deleteBand: (bandId: string) => `/delete/grade-band/${bandId}`,
  },
};
