import {
  LayoutDashboard, Users, GraduationCap, UserCog, Contact, School, Layers, BookOpen,
  ClipboardList, Building2, CalendarRange, Award, FileSpreadsheet, CalendarClock, ShieldCheck,
  KeyRound, FileBarChart, BarChart3, History, Settings, UserPlus, ClipboardCheck, TrendingUp,
  MessageSquare, FileText, Bell, Download, ListChecks, Wallet, User, PieChart, AlertTriangle,
} from 'lucide-react';

export const NAV = {
  admin: [
    { label: 'Dashboard', to: '', icon: LayoutDashboard },
    { label: 'Students', to: 'students', icon: GraduationCap },
    { label: 'Teachers', to: 'teachers', icon: UserCog },
    { label: 'Parents', to: 'parents', icon: Contact },
    { label: 'Classes & Streams', to: 'classes', icon: School },
    { label: 'Subjects', to: 'subjects', icon: BookOpen },
    { label: 'Teacher Assignment', to: 'assignments', icon: ClipboardList },
    { label: 'Departments', to: 'departments', icon: Building2 },
    { label: 'Academic Structure', to: 'academic-structure', icon: CalendarRange },
    { label: 'Timetable Generator', to: 'timetable', icon: CalendarClock },
    { label: 'User Management', to: 'users', icon: Users },
    { label: 'Roles & Permissions', to: 'roles', icon: KeyRound },
    { label: 'Reports', to: 'reports', icon: FileBarChart },
    { label: 'School Analytics', to: 'analytics', icon: BarChart3 },
    { label: 'Audit Logs', to: 'audit-logs', icon: History },
    { label: 'System Settings', to: 'settings', icon: Settings },
  ],
  headteacher: [
    { label: 'Dashboard', to: '', icon: LayoutDashboard },
    { label: 'Performance Analytics', to: 'analytics', icon: BarChart3 },
    { label: 'Attendance Overview', to: 'attendance', icon: ClipboardCheck },
    { label: 'School Reports', to: 'reports', icon: FileBarChart },
    { label: 'Timetable', to: 'timetable', icon: CalendarClock },
    { label: 'Results Approval', to: 'results-approval', icon: Award },
    { label: 'Announcements', to: 'announcements', icon: Bell },
  ],
  classteacher: [
    { label: 'Dashboard', to: '', icon: LayoutDashboard },
    { label: 'My Classes', to: 'my-classes', icon: School },
    { label: 'Student Profiles', to: 'students', icon: GraduationCap },
    { label: 'Attendance', to: 'attendance', icon: ClipboardCheck },
    { label: 'Report Cards', to: 'report-cards', icon: FileText },
    { label: 'Student Performance', to: 'performance', icon: TrendingUp },
    { label: 'Parent Communication', to: 'communication', icon: MessageSquare },
    { label: 'Discipline Records', to: 'discipline', icon: AlertTriangle },
    { label: 'Results', to: 'results', icon: Award },
    { label: 'Timetable', to: 'timetable', icon: CalendarClock },
  ],
  subjectteacher: [
    { label: 'Dashboard', to: '', icon: LayoutDashboard },
    { label: 'Assigned Subjects', to: 'assigned', icon: BookOpen },
    { label: 'Marks Entry', to: 'marks-entry', icon: FileSpreadsheet },
    { label: 'Assessment Management', to: 'assessments', icon: ListChecks },
    { label: 'Grade Book', to: 'gradebook', icon: ClipboardList },
    { label: 'Subject Performance', to: 'performance', icon: PieChart },
    { label: 'Attendance', to: 'attendance', icon: ClipboardCheck },
    { label: 'Timetable', to: 'timetable', icon: CalendarClock },
    { label: 'Reports', to: 'reports', icon: FileBarChart },
  ],
  student: [
    { label: 'Dashboard', to: '', icon: LayoutDashboard },
    { label: 'My Profile', to: 'profile', icon: User },
    { label: 'Academic Results', to: 'results', icon: Award },
    { label: 'Attendance', to: 'attendance', icon: ClipboardCheck },
    { label: 'Subjects', to: 'subjects', icon: BookOpen },
    { label: 'Timetable', to: 'timetable', icon: CalendarClock },
    { label: 'Assignments', to: 'assignments', icon: ListChecks },
    { label: 'Downloads', to: 'downloads', icon: Download },
    { label: 'Notifications', to: 'notifications', icon: Bell },
    { label: 'Performance Trends', to: 'trends', icon: TrendingUp },
  ],
  parent: [
    { label: 'Dashboard', to: '', icon: LayoutDashboard },
    { label: 'Children', to: 'children', icon: Users },
    { label: 'Attendance', to: 'attendance', icon: ClipboardCheck },
    { label: 'Performance', to: 'performance', icon: TrendingUp },
    { label: 'Report Cards', to: 'report-cards', icon: FileText },
    { label: 'Fee Status', to: 'fees', icon: Wallet },
    { label: 'Timetable', to: 'timetable', icon: CalendarClock },
    { label: 'Notifications', to: 'notifications', icon: Bell },
    { label: 'Teacher Communication', to: 'communication', icon: MessageSquare },
  ],
};

export const ROLE_LABELS = {
  admin: 'Administrator', headteacher: 'Headteacher', classteacher: 'Class Teacher',
  subjectteacher: 'Subject Teacher', student: 'Student', parent: 'Parent',
};
