// components/classteacher/shared/constants.ts
export const C = {
  green: "var(--ct-green)",
  greenMid: "var(--ct-green-mid)",
  greenLight: "var(--ct-green-light)",
  gold: "var(--ct-gold)",
  goldLight: "var(--ct-gold-light)",
  goldPale: "var(--ct-gold-pale)",
  cream: "var(--ct-cream)",
  sand: "var(--ct-sand)",
  border: "var(--ct-border)",
  borderLight: "var(--ct-border-light)",
  text: "var(--ct-text)",
  textMid: "var(--ct-text-mid)",
  textMuted: "var(--ct-text-muted)",
  textFaint: "var(--ct-text-faint)",
  white: "var(--ct-white)",
  successBg: "var(--ct-success-bg)",
  successText: "var(--ct-success-text)",
  warnBg: "var(--ct-warn-bg)",
  warnText: "var(--ct-warn-text)",
  dangerBg: "var(--ct-danger-bg)",
  dangerText: "var(--ct-danger-text)",
  sidebarText: "var(--ct-sidebar-text)",
  sidebarMuted: "var(--ct-sidebar-muted)",
  sidebarFaint: "var(--ct-sidebar-faint)",
  sidebarStat: "var(--ct-sidebar-stat)",
  sidebarHover: "var(--ct-sidebar-hover)",
  sidebarActive: "var(--ct-sidebar-active)",
  sidebarBorder: "var(--ct-sidebar-border)",
  topBarBg: "var(--ct-topbar-bg)",
  topBarBorder: "var(--ct-topbar-border)",
};

export const FONT = {
  serif: "'Cormorant Garamond', serif",
  sans: "'Nunito', sans-serif",
};
